name: Deploy to Pis

on:
  push:
    branches: [dev]
    paths-ignore:
      - 'PROJECT_LOG.md'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        port: ${{ secrets.PI_PORT }}
        username: ${{ secrets.PI_USERNAME }}
        key: ${{ secrets.PI_KEY }}

        script: |
          cd ~/project-vesper

          git pull origin dev
          docker compose -f docker-compose.pi.yml down
          docker compose -f docker-compose.pi.yml up -d --build