name: Vesper CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'PROJECT_LOG.md'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        port: ${{ secrets.LINODE_PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git fetch origin main && git reset --hard origin/main
          
          # Restart Docker containers
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up --build -d  # Added --build flag to force rebuild for changes

          # Copy static assets to nginx dir
          echo "Copying static assets.."
          CONTAINER_ID=$(docker compose -f docker-compose.prod.yml ps -q web)
          echo "Container ID: $CONTAINER_ID"
          docker cp "$CONTAINER_ID:/app/app/static/." "${{ secrets.STATIC_PATH }}"
          echo "Copying from $CONTAINER_ID:/app/app/static to ${{ secrets.STATIC_PATH }}"

          echo "Deployment completed at $(date)"
